FROM alpine:3.5
RUN echo '@testing http://nl.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories
RUN apk update
RUN apk add jq imagemagick ffmpeg bash darkhttpd curl wget youtube-dl ca-certificates moreutils@testing
RUN adduser -h /home/flix -s bash -D flix
